### ISSUE TITLE
CMake < 3.5 deprecation warning

### ISSUE THREAD

**Issue by xvitaly** [psi-im/plugins#119]
Please set minimal CMake version to 3.5+.
```
CMake Deprecation Warning at plugins/generic/psimedia/CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.9.4") 
-- gstprovider module will be installed in plugins directory for client: "psi-plus"
CMake Deprecation Warning at plugins/generic/psimedia/psiplugin/CMakeLists.txt:9 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
CMake Deprecation Warning at plugins/generic/psimedia/gstprovider/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  plugins/generic/psimedia/psiplugin/CMakeLists.txt:26 (include)
-- Qt5 found, version 5.15.10
-- Checking for modules 'glib-2.0;gobject-2.0;gthread-2.0'
--   Found glib-2.0, version 2.76.3
--   Found gobject-2.0, version 2.76.3
--   Found gthread-2.0, version 2.76.3
-- Checking for modules 'gstreamer-1.0;gstreamer-app-1.0;gstreamer-base-1.0;gstreamer-audio-1.0;gstreamer-video-1.0'
--   Found gstreamer-1.0, version 1.22.4
--   Found gstreamer-app-1.0, version 1.22.3
--   Found gstreamer-base-1.0, version 1.22.4
--   Found gstreamer-audio-1.0, version 1.22.3
--   Found gstreamer-video-1.0, version 1.22.3
CMake Deprecation Warning at plugins/unix/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- Configuring done (6.5s)
-- Generating done (0.3s)
```

**Comment by Vitozz** [comment]
Fixed in [9fd3307](https://github.com/psi-im/psimedia/commit/9fd3307eb2406bfc29a035c89c18be6160ef5ce0)

**Comment by xvitaly** [comment]
@Vitozz https://github.com/psi-im/plugins/blob/master/unix/CMakeLists.txt#L1 is still not fixed.

**Comment by xvitaly** [comment]
> It has been done, it is good for you?

Yes. This issue has been fixed.
