### ISSUE TITLE
OMEMO plugin doesn't work

### ISSUE THREAD

**Issue by luke-jr** [psi-im/plugins#34]
After enabling the OMEMO plugin, all my contacts say "OMEMO is not available for this contact", even though they all have OMEMO-capable clients ([Conversations](https://github.com/siacs/Conversations))

**Comment by stigger** [comment]
Please try restarting Psi.

**Comment by luke-jr** [comment]
Now it lets me enable it, but no messages get through either way... :/

**Comment by Vitozz** [comment]
Please provide more information. Client version, operating system, os architecture.

**Comment by luke-jr** [comment]
Psi+ v1.3.309 (2018-03-23, Psi:72788ac0, Psi+:df6e90c, webkit)

Linux 4.15.9-gentoo #2 SMP PREEMPT Fri Mar 16 12:32:42 UTC 2018 x86_64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz GenuineIntel GNU/Linux

amd64 for now (will be migrating to POWER9 soon)

**Comment by haegar** [comment]
I had the same problem, after enabling the omemo plugin and restarting psi-plus it just did not do anything.

But it seems adding the button of the omemo plugin to the chat toolbar via the toolbar config dialog has made it more or less work. (Still some strange problems, but too too vague for a bugreport)

**Comment by dos1** [comment]
Yup, seems like until you add it to the toolbar and actually use it, it won't really do much.

**Comment by Neustradamus** [comment]
About the toolbar problem (not new) -> https://chatlogs.jabber.ru/psi-dev@conference.jabber.ru/2018/04/07.html#07:12:45.283092

Recall about OMEMO bugs: https://chatlogs.jabber.ru/psi-dev@conference.jabber.ru/2018/05/02.html#04:36:31.469239
- https://image.ibb.co/gWCYjx/psi_plus_omemo_tls_server_error.png
- https://image.ibb.co/bzVErc/psi_plus_omemo_empty_fingerprint_request.png
- https://image.ibb.co/fbwVjn/psi_plus_omemo_error_psi_no_key_openpgp.png

**Comment by stigger** [comment]
The original problem should be resolved by now.

**Comment by 52871299hzy** [comment]
However, it still doesn't work. After I enabled OMEMO plugin, the message can't be sent.

**Comment by Neustradamus** [comment]
@luke-jr, @haegar, @dos1, @52871299hzy: All work now?

For all people, have you updated your Psi/Psi+?

I would like feedbacks from all users for OMEMO:
- Between Psi, Psi+, and other OMEMO XMPP clients
- OMEMO detection (grey icon / color icon)
- Secure chat (1:1)
- Secure mucroom
- New fingerprints detection
- OMEMO option possibilities (Options->Plugins->OMEMO options), all are good?
-- "Clear devices" and "Refresh" buttons in "Manage Devices" are missing (https://github.com/psi-im/plugins/issues/38)
-- Impossible to remove fingerprints of contacts (https://github.com/psi-im/plugins/issues/37)
-- Regenerate "Own fingerprint" is missing (https://github.com/psi-im/plugins/issues/36)

In the same time:
- OTR feedback too
- GnuPG feedback too

Thanks in advance.

**Comment by luke-jr** [comment]
It seems hit-or-miss for me, but I haven't installed any updates...

**Comment by tehnick** [comment]
@luke-jr Is Client Switcher Plugin is disabled in your case?

**Comment by luke-jr** [comment]
OMEMO Plugin is the only plugin I have installed.

**Comment by Neustradamus** [comment]
@luke-jr: Not possible to update your version?
There were changes since one year...

**Comment by luke-jr** [comment]
I can't get it to build right now (probably not your fault) and don't have time to figure out why. (Likely a GCC bug they won't help with: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85915)

```
x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--as-needed -shared -o libomemoplugin.so .obj/configwidget.o .obj/crypto_ossl.o .obj/crypto_common.o .obj/omemo.o .obj/omemoplugin.o .obj/signal.o .obj/storage.o .obj/qrc_omemoplugin.o .obj/moc_configwidget.o .obj/moc_omemo.o .obj/moc_omemoplugin.o  -lsignal-protocol-c -lcrypto -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Sql -L/usr/lib64/mysql -lQt5Network -lQt5Core -lGL -lpthread  
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libsignal-protocol-c.a(signal_protocol.c.o): In function `__x86_return_thunk':
signal_protocol.c:(.text.__x86_indirect_thunk[__x86_indirect_thunk]+0x0): multiple definition of `__x86_return_thunk'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/crtbeginS.o:crtstuff.c:(.text.__x86_return_thunk[__x86_return_thunk]+0x0): first defined here
```
